# Homebrew formula for Listnr.
#
# This repository doubles as its own Homebrew tap, so there is no separate
# `homebrew-listnr` repo to keep in sync. Homebrew reads formulae from `Formula/`
# at the root of a tapped repository, which is exactly where this lives.
#
#   brew tap rokib16x/listnr https://github.com/rokib16x/listnr
#   brew trust --tap rokib16x/listnr
#   brew install listnr
#
# The two-argument form of `brew tap` is required: the one-argument shorthand
# assumes a repo named `homebrew-<name>`, and this one is named `listnr`.
# `brew trust` is a Homebrew 6 requirement for every third-party tap.
#
# Nothing here needs updating by hand at release time — the release workflow
# rewrites url, sha256 and version itself. See packaging/README.md.
#
class Listnr < Formula
  desc "Local meeting listener: mic + system audio to a multi-speaker transcript"
  homepage "https://github.com/rokib16x/listnr"
  # url and sha256 are rewritten by the release workflow on every tag; see the
  # "Point the formula at the new release" step. Do not hand-edit them.
  #
  # There is deliberately no `version`: Homebrew scans it out of the URL, and
  # `brew audit --strict` rejects an explicit one as redundant.
  url "https://github.com/rokib16x/listnr/releases/download/v0.1.4-beta/listnr-0.1.4-beta-macos-arm64.tar.gz"
  sha256 "f55bdcb69ce7750268734636ead52f49adafde7451790d72992bc35fc91e3a94"
  license "MIT"

  # Both are hard requirements, not preferences. Listnr runs Whisper on the
  # Neural Engine and captures system audio through ScreenCaptureKit, so an
  # Intel Mac or an older macOS cannot run it at all — `listnr doctor` refuses to
  # start. Declaring them here turns that into an install-time refusal with a
  # clear message rather than a confusing runtime one.
  depends_on arch: :arm64
  depends_on macos: :sonoma

  # This installs the prebuilt binary from the release rather than compiling.
  # Two reasons: a source build takes several minutes because it compiles
  # WhisperKit, and the released binary is signed with a Developer ID and
  # notarized — building locally would discard that. There is deliberately no
  # `head` spec: a source build would need an entirely separate install path,
  # and the release artefact is the thing that is actually tested.
  #
  # No xcode build dependency either, for the same reason: nothing is compiled.
  def install
    bin.install "listnr"

    # Generated by the release workflow from swift-argument-parser and shipped in
    # the tarball, so there is nothing to run here. Note zsh's file is `_listnr`
    # while bash's is installed under the command name.
    bash_completion.install "completions/listnr.bash" => "listnr"
    zsh_completion.install "completions/_listnr"
    fish_completion.install "completions/listnr.fish"

    man1.install Dir["man/*.1"]
  end

  def caveats
    <<~EOS
      Listnr needs two macOS permissions before it can capture anything:

        listnr setup      grant Microphone + Screen & System Audio Recording
        listnr doctor     verify them

      macOS attaches both permissions to your *terminal application*, not to the
      listnr binary. `brew upgrade` will not re-prompt, but switching from
      Terminal to iTerm (or any other terminal) means granting them again.

      Speech models download on first use, not during this install. They land in
      ~/Documents/huggingface and range from 139 MB (English) to about 1.5 GB.
      To fetch one ahead of a call:

        listnr models download whisper-base.en

      Recording other people without their consent is illegal in many places.
      Read the README before using this on a call.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/listnr --version")

    # The model registry is the only meaningful thing testable in a sandbox: no
    # audio hardware, no TCC permissions, no network.
    assert_match "whisper-base.en", shell_output("#{bin}/listnr models list")

    # An unknown model must fail loudly rather than fall back to another one.
    assert_match "unknown model", shell_output("#{bin}/listnr models download nope 2>&1", 1)

    assert_match "#compdef listnr",
                 shell_output("#{bin}/listnr --generate-completion-script zsh")
  end
end
